backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use common\models\SignupForm;
use common\models\Patient;
use common\models\EdLocation;
use common\models\MailRecipient;
use yii\filters\VerbFilter;
/**
 * Site controller
 */ 

class SiteController extends Controller {
     
    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'login', 'error', 'register', 'patient-sp', 'bed-sp','test-mail',
                            'dashboard-index','ward-dashboard'
                            ],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
     public function actionIndex() {
           
        $data = Patient::countInfoEd(); 
        
        // Ordering NULL values to the last by placing a minus(-) sign in front of the
        // column name
             
        $locations = EdLocation::find()->where(['=', 'location_type', 1])
                                       ->orderBy('-[location_order] DESC, name')->all(); 
        
        return $this->render('index',[
                'data' => $data,
                'locations' => $locations,
                'model' => new Patient()
            ]);
        
    }
     
    public function actionDashboardIndex() {
        $data = Patient::countInfoEd(); 
        
        // Ordering NULL values to the last by placing a minus(-) sign in front of the
        // column name
        $locations = EdLocation::find()
//                ->select(['*',"TRIM(TRAILING '}' FROM TRIM(LEADING '{' FROM NAME)) as trim_name"])
                ->select(['*',"name as trim_name"])
                ->where(['=', 'location_type', 1])
                ->orderBy('-[location_column_order] DESC, location_column_suborder')->all(); 


        return $this->render('dashboard-index',[
            'data' => $data,
            'locations' => $locations,
            'patients' => Patient::getUnassignedPatientModel(),
            'model' => new Patient()
        ]);
        
    }
    public function actionWardDashboard() {
        $data = Patient::countInfoEd(); 
        
        // Ordering NULL values to the last by placing a minus(-) sign in front of the
        // column name
        $locations = EdLocation::find()
//                ->select(['*',"TRIM(TRAILING '}' FROM TRIM(LEADING '{' FROM NAME)) as trim_name"])
                ->select(['*',"name as trim_name"])
                ->where(['=', 'location_type', 1])
                ->orderBy('-[location_column_order] DESC, location_column_suborder')->all()
                ; 
        return $this->render('ward-dashboard',[
            'data' => $data,
            'locations' => $locations,
            'patients' => Patient::getUnassignedPatientModel(),
            'model' => new Patient()
        ]);
        
    }

    public function actionLogin() {
        $this->layout = 'register';
            
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                    'model' => $model,
            ]);
        }
    }   
    
    public function actionRegister() {
       $this->layout = 'register';
       
       if (!\Yii::$app->user->isGuest) { 
            return $this->goHome();
        }

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }
        
        return $this->render('register', [
                'model' => $model,
        ]);
    }  

    public function actionLogout() {
        Yii::$app->user->logout();
         
        return $this->goHome();
    } 
    
    //Extra Test Code

    public function actionPatientSp() {
        echo __LINE__ . "--" . __FILE__;
        echo "<pre>";
            print_r(\common\components\SPHelper::getAllEdPatients());
        echo "</pre>";
        exit;
        return $this->goHome();
    }
    
      public function actionTestMail() {
        try{
            $data = Patient::countMailInfoEd(); 
            $html = $this->renderPartial('mail-template2',['data' => $data]);
            Yii::$app->mailer->compose()
              ->setFrom('edtracker@hse.ie')
              ->setTo('enda.furey@twdc.ie')
              ->setSubject("Current ED Statistics")
              ->setHtmlBody($html)
              ->send();
            echo 'Mail Send';exit;
        } catch (InvalidParamException $e) {
                echo 'Error';exit();
            throw new BadRequestHttpException($e->getMessage());
        }        
   } 
        

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ]
        ];
    }
    
    public function filters()
    {
        
        return [
            //<any other filters here>
            ['booster.filters.BootstrapFilter - delete']
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

backend/views/site/assign-patient.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\Patient;

/* @var $this yii\web\View */
/* @var $model common\models\Cleaning */
/* @var $form yii\widgets\ActiveForm */
?>  
<?php
$form = ActiveForm::begin([
            'action' => Yii::$app->urlManager->createUrl(['patient/update-location-data']),
            'options' => [
                'data' => [
                    'on-done' => 'saved-consultant'
                ],
            ],
            'id' => 'save-update-location-data-form',
            'enableAjaxValidation' => false,
            'enableClientValidation' => true,
        ]);  
//print_r($ward_list);die;
?>
<div class="modal-header">
    <h3 id="referral-form-heading" class="modal-title">Add Patient Location</h3>
</div>

<div class="modal-body bgm-white  p-t-5">            


    <div class=" m-t-10 " id="part_1">
        <div class ="p-l-0">
            <input type="hidden" id="assign-id" name="Patient[ed_location]" value="" ><br />
            <div  class=" c-gray center ">
                <?php
                echo $form->field($model, 'Patient_id', Yii::$app->params['htmlTemplate']['select'])
                        ->dropDownList(ArrayHelper::map(Patient::getUnassignedPatientModel(), 'Patient_id', 'patient_name'), ['prompt' => '', 'style' => 'margin-top:10px;'])->label('Patient Name');
                ?>            
            </div>
         </div> 
        <div class="clearfix"></div>
        <div class=" m-t-10 c-gray " >
            <h4 class="m-b-20">Enter Verification Code</h4>
            <?php echo $form->field($model, 'code', Yii::$app->params['htmlTemplate']['inputPassword'])->passwordInput(['autocomplete' => 'off', 'maxlength' => true, 'onkeyup' => 'fncheckpass( this.value, "' . \yii\helpers\Url::to(['accesspass/checkpass']) . '" , "checkcode")'])->label(false); ?>
            <div style='color:red;' class='fill_error'>Please Fill the correct code</div>
            <div class="center col-sm-12 m-b-20">
                <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success btn-lg pull-right accesspass-btn' : 'btn btn-primary btn-lg pull-right', 'disabled' => 'disabled']) ?>
            </div>
        </div>
    </div> 
    <div class="clearfix"></div>
</div>  


<div class="clearfix"></div>

<div id="dismiss" class="modal-footer">
    <button  type="button" class="btn btn-link" data-dismiss="modal">Close</button>
</div>
<input type='hidden' value='0' id='checkcode' />
<?php ActiveForm::end(); ?>
<div class="clearfix"></div>

backend/views/site/dashboard-index.php
<?php
/* @var $this yii\web\View */
use common\components\NameHelper;
use common\components\ArrayHelpers;
use common\components\CommonHelper;
$this->title = 'UHG Emergency Department Patient Tracking System';
?>


<style>
    .mini-charts-item{
        height: 80px;
    }
    .innerBox {
        height: 62px;
        width: inherit;
    }
    .waitingBox {
        height: auto!important;
        width: inherit;
    }
    .p-t-65 {
        padding-top: 65px!important;
    }

    h4, .h4 {
        font-size: 24px;
        padding-left: 5px;
        margin-top: 0px;
    }
    .col-custom{
        width: 9.5%;
        float:left;
    }
    .float-right{
        float: right;
    }
    .float-left{
        float: left;
    }
    .m-r-2{
        margin-right: 2px!important;
    }
    .outer-div{
        min-height: 210px;
        font-size: 22px;
    }
    @media (min-width: 1300px){
        .modal-elg {
            width: 1800px;
        }
    }
</style>

<?php
    echo $this->render('../partials/partial-pab', [
        'data' => $data,
    ]);
?>

<div class="modal fade" data-modal-color="bluegray" id="replace-form" data-backdrop="static" data-keyboard="true" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;z-index: 1050;">
    <div class="modal-dialog modal-lg">
        <div id="replaceData" class="modal-content">
             
            <?= $this->render('../forms/replace-form', ['model' => $model]) ?>

        </div>
    </div>
</div>

<div class="modal fade" data-modal-color="bluegray" id="assign-patient" data-backdrop="static" data-keyboard="true" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;z-index: 1050;">
    <div class="modal-dialog">
        <div id="AssignPatient" class="modal-content">
            <?= $this->render('assign-patient', ['model' => $model]) ?>

        </div>
    </div>
</div>
<!-- Episodes modal -->
<div class="modal fade" data-modal-color="bluegray" id="episodes-view" data-backdrop="static" data-keyboard="true" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;z-index: 1050;">
    <div class="modal-dialog  modal-lg">
        <div class="modal-header bgm-gray">
            <h4 id="" class="modal-title">Episodes View</h4>
        </div>
        <div id="episodesData" class="modal-body bgm-white p-t-10">

        </div>
        <div id="dismiss" class="modal-footer bgm-gray">
            <button  type="button" class="btn btn-link" data-dismiss="modal">Close</button>
        </div>

    </div>
</div>

<div class="modal fade" data-modal-color="bluegray" id="discharge-form" data-backdrop="static" data-keyboard="true" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;z-index: 1050;">
    <div class="modal-dialog">
        <div id="dischargeData" class="modal-content">
            <?= $this->render('../forms/discharge-form', ['model' => $model]) ?>

        </div>
    </div>
</div>
<div class="row m-l-5">
<?php
$column = null;
foreach ($locations as $location) :
    if($column != $location->location_column_order){
        if(!$column){
            $column = $location->location_column_order;
        } else {
            $column = $location->location_column_order;
            //If there is previous col-custom div then closing it
            echo '</div>';
        }
        //Starting a new row on change of column order
        echo '<div class =" col-custom m-r-5">';
    }
       
    if(!empty($location->patients)):
        $flagDischarge = true;
        //$patient = $location->patients;
         foreach ($location->patients as $patient):
         if(!$patient->is_discharge ):
                $flagDischarge = false;
                echo CommonHelper::getPatientCell($location->name, $patient);
         endif;
        endforeach;
        if($flagDischarge):
            echo CommonHelper::getEmptyCell($location);
        endif;
    else:
        echo CommonHelper::getEmptyCell($location);
    endif;
endforeach;
?>
<!--Closing the last column ie; <div class="col-custom">-->
</div> 

<!--Waiting Room Patients Listing-->
<div class="col-custom ">
<?php 

$halfCount = (int) (count($patients) / 2);
$patientCount = 0;
foreach ($patients as $patient) {
    $patientCount++;
    echo CommonHelper::getWaitingPatientCell($patient);
    if ($patientCount == $halfCount) { 
        echo '</div><div class="col-custom">';
    }
}
?>

<div class="modal fade " data-modal-color="bluegray" id="select-field" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;z-index: 1050;">
    <div class="modal-dialog modal-elg">
        <div id="" class="modal-content">
             <?= $this->render('../forms/select-field', ['model' => $model]) ?>
        </div>
    </div>
</div>
    

<div class="modal fade" data-modal-color="bluegray" id="dropdown-view" data-backdrop="static" data-keyboard="true" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;z-index: 1050;">
    <div class="modal-dialog modal-lg">
        <div class="modal-header row bgm-gray">
            <div id="" class=" col-sm-6 modal-title h4">Patient View</div>
            <div class="col-sm-6">
                <button type="button" class="btn btn-link pull-right c-white" data-dismiss="modal"><span class="md-close md-2x"></span></button>
            </div>
        </div>
        <div id="dropdownData" class="modal-body bgm-white p-t-10">

        </div>
        <div id="dismiss" class="modal-footer bgm-gray">
            <button  type="button" class="btn btn-link" data-dismiss="modal">Close</button>
        </div>

    </div>
</div>
<script type="text/javascript">
    $('.replaceClass').click(function(){ 
        var element = $(this);
        name = element.data('name');
        boardNumber = element.data('boardnumber');
        episodeNumber = element.data('episodenumber');
        dob = element.data('dob');
        address = element.data('address');
        age = element.data('age');
        id = element.data('id');
        edStream = element.data('ed_stream');
        edLocation = element.data('ed_location');
        edDoctor = element.data('ed_doctor');
        edNurse = element.data('ed_nurse');
        
        admission_date = element.data('admission_date');
        
        //For Episode Popup
        $('#episodeAnchor').data('id',id);
        
        $('#dropdownAnchor').data('id',id);
        $('#episodeAnchor').data('board_number',boardNumber);
        
        //For Discharge Popup
        $('#dischargeAnchor').data('id',id);
        $('#dischargeAnchor').data('boardnumber',boardNumber);
        $('#dischargeAnchor').data('name',name);
        $('#dischargeAnchor').data('age',age);
        
        $('#dietetianAnchor').data('boardnumber', boardNumber)
        $('#dietetianAnchor').data('episodeNumber', episodeNumber)
        $('#dietetianAnchor').data('name', name)

        
        $('#patient-patient_name').val(name);
        $('#patient-dob').val(dob);
        $('#patient-age').val(age);
        $('#patient-address').val(address);
        $('#patient-admission_date').val(admission_date);
        $('#patient-board_number').val(boardNumber);
        $('#replace-id').val(id);
        $('#patient-referral_type').val('');
        $('#replace-id').val(id);
        $('#patient-ed_location').val($.trim(edLocation));
        $('#patient-ed_stream').val($.trim(edStream));
        $('#patient-ed_doctor').val($.trim(edDoctor));
        $('#patient-ed_nurse').val(edNurse);
        $('.toggle').addClass('hide');
        $('#part_1').removeClass('hide');
        focusInputs();
        $('#replace-form').modal({
            show: 'true',
            keyboard: true
        });
        
    });
    
    $('.dietetianClass').click(function(e){
        $('#nursereferral-board_number').val($('#dietetianAnchor').data('boardnumber'));
        $('#nursereferral-episode_number').val($('#dietetianAnchor').data('episodeNumber'));
        $('#nursereferral-patient_name').val($('#dietetianAnchor').data('name'));
                       
        $('#loader').hide();
        $('#dietetian-form').modal({
              show: 'true',
              keyboard: true 
         }); 

   });
    
    $('.assignPatient').click(function(){
       
        id = $(this).data('ed_location');
        console.log(id);
        $('#assign-id').val(id);
        $('#assign-patient').modal({
            show: 'true',
            keyboard: true
        });
        
    });
    $('#save-replace-form').on('submit', function (e) {

        e.preventDefault();
        e.stopImmediatePropagation();
        $('#fill_error').hide();
        currentElement = e;
        var showId = $(e).data('show_id');
        flag = true;
        if ($('#checkcode').val() == '1') {

            $('#fill_error').hide();
        } else {
            flag = false;
            $('#fill_error').show();
        }
        if (flag) {
            $('#loader').show();
            $('#patient-ed_doctor').attr("disabled", false);             
            $('#patient-ed_location').attr("disabled", false);             
            $('#patient-ed_nurse').attr("disabled", false);             
            $('#patient-referral_type').attr("disabled", false);  
            submitFormHandle(e);
        } 
    });
    
    $('#save-update-location-data-form').on('submit', function (e) {

        e.preventDefault();
        e.stopImmediatePropagation();
        $('#fill_error').hide();
        currentElement = e;
        var showId = $(e).data('show_id');
        flag = true;
        if ($('#checkcode').val() == '1') {

            $('#fill_error').hide();
        } else {
            flag = false;
            $('#fill_error').show();
        }
        if (flag) {
            $('#loader').show();
            submitFormHandle(e);
        }
    });

    $('.dropdownClass').click(function(){
        id = $(this).data('id');
        var url = '<?=Yii::$app->urlManager->createUrl(['patient/get-dropdowndata?id='])?>' + id;
//        console.log(url);
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: url,
            success: function(data) {
                if(data.success) {
                    $('#dropdownData').html(data.dropdownData);
                    $('#loader').hide();
                    $('#dropdown-view').modal({
                        show: 'true',
                        keyboard: true
                    });
                } 
            }
        });
        
        
    });
    
        
$('.referralSelectClear').click(function(e){
   $('#patient-referral_type').val('');
   $('#select-field').modal('toggle');
});

    
    </script>
    
<?= $this->registerJs('reload(30000, 30000);');?>

backend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm; 

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Login';
?>

  
<div class="lc-block toggled" id="l-login">
    <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
    
    <?= $form->field($model, 'username', Yii::$app->params['htmlTemplate']['email'])->input('text', ['placeholder' => 'Email Address']) ?>
    <?= $form->field($model, 'password', Yii::$app->params['htmlTemplate']['password'])->passwordInput(['placeholder' => 'Password']) ?>

    <?= $form->field($model, 'rememberMe', Yii::$app->params['htmlTemplate']['checkbox'])->checkbox(array(), false) ?>

    <button class="btn btn-login btn-danger btn-float" type="submit"><i class="md md-arrow-forward"></i></button>

    <ul class="login-navigation">
        <li class="bgm-red"><?= Html::a('Register', ['/site/register']) ?></li>
        <li class="bgm-orange">Forgot Password?</li>
    </ul>
    <?php ActiveForm::end(); ?>
</div>

backend/views/site/mail-template.php
<?php 
use common\components\ArrayHelpers;
?>

<style>

/*    .ed-stats-color{
        background-color: #607d8b!important;    
    }
    #mail-table {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    #mail-table td, #mail-table th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    #mail-table tr:nth-child(even){background-color: #f2f2f2;}

    #mail-table tr:hover {background-color: #ddd;}

    #mailtable th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #4CAF50;
        color: white;
    }*/
/*    .center {
        text-align: center;
        margin-right: 1em;
      }*/
/*  @media (max-width: 768px) {
        .cu-col-sm-2 {
            width: 100%;
            float: left;
        }
    }
  @media (min-width: 768px) {
        .cu-col-sm-2 {
            width: 60%;
            float: left;
        }
    }
    
    .cu-col-sm-2 {
        position: relative;
        min-height: 1px;
        padding-left: 12px;
        padding-right: 12px;
    }*/
</style>
Current Total Patients : <?=$data['edPatients']?> <br>
Triage : <?php echo $data['awaitingTriage'].' ('.$data['awaitingTriageAmbulance'].' Ambulance)';?> <br>
Patients Awaiting Beds : <?php echo $data['awaitingBed'].' (Longest: '.ArrayHelpers::getHourMin($data['longestInEd']).')'?> <br>
Patient over 9 Hours : <?php echo $data['>9']?> <br>
Patient over 24 Hours : <?php echo $data['>24'];?> <br>
Patient over 75 : <?=$data['75+p']?> <br>
Patients over 75 greater than 9 hours : <?=$data['75+p>9']?><br>
Patients over 75 greater than 24 hours : <?=$data['75+p>24']?> <br>
Number of patients 0-4 hours : <?=$data['0-4']?> <br>
Number of patients 4-8 hours : <?=$data['4-8']?> <br>
Number of patients >8 hours : <?=$data['>8']?> <br>
Patients under 16 Yrs : <?= $data['patients_under_16'].'<br>'.(($data['edPatients']) ? '('. round((100*$data['patients_under_16']/$data['edPatients']),2).'%)' : 0 );?>  <br>
<h3>Co-ordinated Patients</h3>  <br>
C1 : <?=$data['C1']?> <br>
 C2 : <?=$data['C2']?> <br>
 C3 : <?=$data['C3']?> <br>
C4 : <?=$data['C4']?> <br>
C5 : <?=$data['C5']?> <br>
 M1 : <?=$data['M1']?> <br>
M2 : <?=$data['M2']?> <br>
M3 : <?=$data['M3']?> <br>
M4 : <?=$data['M4']?> <br>
M5 : <?=$data['M5']?>

backend/views/site/mail-template2.php
<?php 
use common\components\ArrayHelpers;
?>



<h3>Emergency Department (All Patients) - Current Status </h3><br>
Total Patients: <?=$data['edPatients']?> (Longest: <?=ArrayHelpers::getHourMin($data['longestInEd'])?>) <br>
Total Admitted: <?=$data['pnab']?><br>
Total Not Admitted:<?=$data['pab']?><br>
Awaiting Discharge:<?=$data['awaitingDischarge']?><br>

Triage: <?php echo $data['awaitingTriage'].' ('.$data['awaitingTriageAmbulance'].' Ambulance)';?> <br>
Under-16(Paeds): <?=$data['patients_under_16']?> <br> 
<br>
<h3>ED Patients (Not Admitted) - Current Status </h3><br>
Total Patients: <?=$data['pab']?> (Longest: <?=ArrayHelpers::getHourMin($data['pab_longest'])?>) <br>
Over 9 Hours: <?=$data['pab_p>9']?> <br>
Over 24 Hours: <?=$data['pab_p>24']?> <br>
Patients over 75: <?=$data['pab_>75']?><br>
Over 75(Greater Than 9 Hours): <?=$data['pab_75+p>9']?> <br>
Over 75(Greater Than 24 Hours): <?=$data['pab_75+p>24']?> <br>
<br>
Number of Patients 0-4 hours: <?=$data['pab_0-4']?> <br>
Number of Patients 4-8 hours: <?=$data['pab_4-8']?> <br>
Number of Patients >8 hours: <?=$data['pab_>8']?> <br>
<br>

<h3>ED Patients (Admitted) - Current Status</h3> <br>
Total Patients: <?=$data['pnab']?>  (Longest: <?=ArrayHelpers::getHourMin($data['pnab_longest'])?>) <br>
Over 9 Hours: <?=$data['pnab_p>9']?> <br>
Over 24 Hours: <?=$data['pnab_p>24']?> <br>
Patients over 75: <?=$data['pnab_>75']?><br>
Over 75(Greater Than 9 Hours): <?=$data['pnab_75+p>9']?> <br>
Over 75(Greater Than 24 Hours): <?=$data['pnab_75+p>24']?> <br>
<br>
Number of Patients 0-4 hours: <?=$data['pnab_0-4']?> <br>
Number of Patients 4-8 hours: <?=$data['pnab_4-8']?> <br>
Number of Patients >8 hours: <?=$data['pnab_>8']?> <br>
<br>
<h3>Co-ordinated Patients</h3>  <br>
C1 : <?=$data['C1']?> <br>
C2 : <?=$data['C2']?> <br>
C3 : <?=$data['C3']?> <br>
C4 : <?=$data['C4']?> <br>
C5 : <?=$data['C5']?> <br>
M1 : <?=$data['M1']?> <br>
M2 : <?=$data['M2']?> <br>
M3 : <?=$data['M3']?> <br>
M4 : <?=$data['M4']?> <br>
M5 : <?=$data['M5']?> <br>

Other Category : <?=$data['OtherCoordCode']?>